# Set the Docker Compose file format
version: '3.9'

# Define toolbox network
networks:
  backend:
    name: dev-network
    driver: bridge

# Define volumes
volumes:
  mariadb-storage:
    driver: local

# Define the services that make up the project
services:
  website:
    build:
      context: .
    image: website:dev
    #command: ["php", "-dxdebug.mode=profile", "-dxdebug.start_with_request=yes", "-S", "0.0.0.0:8080", "router.php"]
    command: ["php", "-S", "0.0.0.0:8080", "router.php"]
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - '.:/var/www/html'
    networks:
      - backend
    ports:
      - '80:8080'

  mariadb:
    image: mariadb:10.9
    environment:
      TZ: Asia/Ho_Chi_Minh
      MARIADB_DATABASE: 'tourist_db'
      MARIADB_USER: 'vntourist'
      MARIADB_PASSWORD: 'tourist'
      MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - 'mariadb-storage:/var/lib/mysql'
      - './database:/docker-entrypoint-initdb.d'
    networks:
      - backend
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping' ]
      retries: 3
      timeout: 5s

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      TZ: Asia/Ho_Chi_Minh
      PMA_HOST: 'mariadb'
      PMA_USER: 'vntourist'
      PMA_PASSWORD: 'tourist'
      UPLOAD_LIMIT: '300M'
    depends_on:
      - mariadb
    networks:
      - backend
    ports:
      - '20080:80'